### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by torarnv** [jspahrsummers/Microverse#19]
Getting these build errors building with Xcode 13 beta 4 on an Intel Mac.

![image](https://user-images.githubusercontent.com/7536/128632798-aab1b601-2c48-4d49-80be-c3d458c186db.png)

I'm not on macOS 12 locally but it should at least build (so I can run it on my M1 with macOS 12), so not sure what's going on?

**Comment by torarnv** [comment]
Very cool you're doing this project btw! ❤️  Have you considered a command line tool or mode as well? `vftool` doesn't seem to have any macOS guest support yet

**Comment by torarnv** [comment]
Xcode must be confused:

![image](https://user-images.githubusercontent.com/7536/128633060-8dfade18-de89-4d1e-a8ba-ff89f2690025.png)

**Comment by jspahrsummers** [comment]
Are you sure it doesn't build and run? I was having IDE integration issues like what you've described: https://github.com/jspahrsummers/Microverse/issues/15

> Have you considered a command line tool or mode as well? `vftool` doesn't seem to have any macOS guest support yet

What would this ideally look like? A GUI application is needed to connect to the guest OS' display anyways.

**Comment by jspahrsummers** [comment]
@mxswd got it to build on Intel, so I think it's just an Xcode issue: https://twitter.com/mxswd/status/1424357718014496772

**Comment by mxswd** [comment]
Yeah so the headers for macOS VM configuration are all #ifdef arm64, so the symbols are missing on x86. I don't know why they did that when they had a perfectly good `isSupported` method on the configuration!

I sprinkled a few arch ifdefs to skip the macOS references and it builds, but it seems macOS only supports macOS VMs on M1 devices not intel. 

I can probably send the branch in about 18 hours time, fixing it messed up a bunch of swift UI.

**Comment by torarnv** [comment]
>> Have you considered a command line tool or mode as well? vftool doesn't seem to have any macOS guest support yet

> What would this ideally look like? A GUI application is needed to connect to the guest OS' display anyways.

In a CI setting you might want to run a headless node that you connect to with screen sharing/VNC only when needed (to debug things). With `vftool` I guess you'd spawn a few VMs and background `vftool`, and then use `ps` to inspect running VMs. One possibly improvement to that flow would be more of a `docker start` and `docker ps` flow, where the program keeps track of running VMs.

My use-case is something I can use as a backend for [OpenNebula](https://opennebula.io/), as a [virtualization driver](https://docs.opennebula.io/6.0/integration_and_development/infrastructure_drivers_development/devel-vmm.html).

**Comment by jspahrsummers** [comment]
> > > Have you considered a command line tool or mode as well? vftool doesn't seem to have any macOS guest support yet
> 
> > What would this ideally look like? A GUI application is needed to connect to the guest OS' display anyways.
> 
> In a CI setting you might want to run a headless node that you connect to with screen sharing/VNC only when needed (to debug things). With `vftool` I guess you'd spawn a few VMs and background `vftool`, and then use `ps` to inspect running VMs. One possibly improvement to that flow would be more of a `docker start` and `docker ps` flow, where the program keeps track of running VMs.
> 
> My use-case is something I can use as a backend for [OpenNebula](https://opennebula.io/), as a [virtualization driver](https://docs.opennebula.io/6.0/integration_and_development/infrastructure_drivers_development/devel-vmm.html).

Ah, I see. Well, this is primarily a tool for my own purposes, so although I'm not opposed to adding something like that in the future, it will be quite low on my priority list. Maybe this would be worth a PR into `vftool` itself?

**Comment by jspahrsummers** [comment]
> Yeah so the headers for macOS VM configuration are all #ifdef arm64, so the symbols are missing on x86. I don't know why they did that when they had a perfectly good `isSupported` method on the configuration!
> 
> I sprinkled a few arch ifdefs to skip the macOS references and it builds, but it seems macOS only supports macOS VMs on M1 devices not intel.
> 
> I can probably send the branch in about 18 hours time, fixing it messed up a bunch of swift UI.

@mxswd Thanks for highlighting this—it explains why I was seeing errors in the IDE that didn't actually stop me from building and running on arm64.

I "fixed" it by disabling all macOS paths in 9a2ec9f680f028ef43b44c404009594232a8d9d8. Apologies for getting out ahead of your branch, just wanted to get rid of all the red now that I understand the origin. 😅

**Comment by torarnv** [comment]
> Ah, I see. Well, this is primarily a tool for my own purposes, so although I'm not opposed to adding something like that in the future, it will be quite low on my priority list. Maybe this would be worth a PR into `vftool` itself?

Yeah, you're right, probably best to implement that in `vftool` directly. Just wanted to check if you had any plans in that area before I started hacking on `vftool` ☺️  Thanks!
