### ISSUE TITLE
GUI for Linux

### ISSUE THREAD

**Issue by jspahrsummers** [jspahrsummers/Microverse#21]
Unlike the macOS VM stuff, `VZMacGraphicsDisplayConfiguration` seems to be available on x86_64, so it's _possible_ that it might work to attach a display to a Linux VM.

**Comment by mxswd** [comment]
It seems possible. Firstly, `VZMacGraphicsDeviceConfiguration` is the only subclass of `VZGraphicsDeviceConfiguration`. When you attach it to a linux vm you get this extra PCI device.

<img width="672" alt="Screen Shot 2021-08-09 at 11 26 50 PM" src="https://user-images.githubusercontent.com/136101/128700395-da5950b3-9121-4be1-898d-37af1a57fcb3.png">

Has anyone implemented this graphics device? Does it have the same API as something else? Maybe the people who ported linux to M1 did? It seems that AppleParavirtIOSurface.kext only has an arm64 slice, so maybe that's the client of the PCI device on macOS VMs?

**Comment by jspahrsummers** [comment]
I sort of interpret the symbol name as "hardware that looks like a Mac computer's display," so I would think that a Linux installation with the appropriate drivers to run on actual Mac hardware could make use of it.

**Comment by mxswd** [comment]
Yeah I agree.

It seems that kernel 5.11 in Ubuntu 21.04 doesn't have a driver for it.

<img width="620" alt="Screen Shot 2021-08-09 at 11 58 16 PM" src="https://user-images.githubusercontent.com/136101/128702690-177ab1bc-2c4b-4e01-8472-25d562560a73.png">

**Comment by mxswd** [comment]
Searching the GitHub mirror of Linux I couldn't find anything that implemented the PCI Id [106b:eeee]. '106b' is Apple, 'eeee' is also not in any databases.

**Comment by jspahrsummers** [comment]
Linux support removed in #29.
